import { type IProductCard } from '@/shared/types';

export const paintingsList: IProductCard[] = [
  {
    id: 1,
    photo: '/pic_01.jpg',
    artist: {
      id: 1,
      name: 'Алексей',
      lastname: 'Харламов',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Подруги',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Фигуративное искусство',
    },
    genre: {
      id: 1,
      name: 'Портрет',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 2,
    photo: '/pic_02.jpg',
    artist: {
      id: 1,
      name: 'Юлий',
      lastname: 'Клевер',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Оттепель',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Абстракция',
    },
    genre: {
      id: 1,
      name: 'Портрет',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 3,
    photo: '/pic_03.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 4,
    photo: '/pic_04.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Графика',
    },
    style: {
      id: 1,
      name: 'Концептуальное искусство',
    },
    genre: {
      id: 1,
      name: 'Городской пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'бумага',
    material_tablet: 'акварель',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 5,
    photo: '/pic_05.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Фотография',
    },
    style: {
      id: 1,
      name: 'Абстракция',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'акрил',
    material_tablet: 'дерево',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 6,
    photo: '/pic_06.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Минимализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масляная пастель',
    material_tablet: 'бумага',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 7,
    photo: '/pic_07.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Print',
    },
    style: {
      id: 1,
      name: 'Pop Art',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 8,
    photo: '/pic_08.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Digital',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 9,
    photo: '/pic_09.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 10,
    photo: '/pic_10.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 11,
    photo: '/pic_11.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
  {
    id: 12,
    photo: '/pic_12.jpg',
    artist: {
      id: 1,
      name: 'Григорий',
      lastname: 'Гуркин',
      bio: '',
      date_of_birth: '',
      city_of_residence: '',
      solo_shows: [],
      group_shows: [],
    },
    title: 'Озеро горных духов',
    category: {
      id: 1,
      name: 'Живопись',
    },
    style: {
      id: 1,
      name: 'Сюрреализм',
    },
    genre: {
      id: 1,
      name: 'Пейзаж',
    },
    description:
      'Созерцание природы сподвигло меня к исследованию формы пятен и их движения по холсту во время творческого процесса, это способствовало не только формированию композиции, но и рождению сюжета. Цвет в полотнах развивается и трансформируется от холста к холсту, передавая изменения эмоционального состояния.',
    year_create: '1975',
    width: 200,
    height: 300,
    material_work: 'масло',
    material_tablet: 'холст',
    unique: true,
    investment_attractiveness: true,
    price: '75 000',
  },
];
