export const paintingsList = [
  {
    id: 1,
    image: '/pic_01.jpg',
    artist: 'ХАРЛАМОВ Алексей',
    name: 'Подруги',
    description: 'Картина, живопись. Холст, масло.',
    price: '75 000',
  },
  {
    id: 2,
    image: '/pic_02.jpg',
    artist: 'КЛЕВЕР Юлий',
    name: 'Оттепель',
    description: 'Холст, масло. Абстракция, Пейзаж.',
    price: '75 000',
  },
  {
    id: 3,
    image: '/pic_03.jpg',
    artist: 'ГУРКИН Григорий',
    name: 'Озеро горных духов',
    description: 'Холст, масло. Абстракция, Пейзаж.',
    price: '75 000',
  },
  {
    id: 4,
    image: '/pic_04.jpg',
    artist: 'Василий Иванович Суриков',
    name: 'Городской пейзаж',
    description: 'Холст, масло. Абстракция, Пейзаж.',
    price: '75 000',
  },
  {
    id: 5,
    image: '/pic_05.jpg',
    artist: 'Высоковских А.П.',
    name: 'Осирис',
    description: '30×65 см, холст, масло, 2005 г.',
    price: '10 000',
  },
  {
    id: 6,
    image: '/pic_06.jpg',
    artist: 'Князев И.М',
    name: 'Зима',
    description: '40×30 см, холст, масло, 2006 г.',
    price: '20 000',
  },
  {
    id: 7,
    image: '/pic_07.jpg',
    artist: 'Матис А.,',
    name: 'Лиловый закат',
    description: '42×61 см, бумага, гуашь, 2005 г.',
    price: '6 000',
  },
  {
    id: 8,
    image: '/pic_08.jpg',
    artist: 'Фатеева А.В',
    name: 'Причал в финляндии',
    description: '65×35 см, холст, масло, 2012 г.',
    price: '7 000',
  },
  {
    id: 9,
    image: '/pic_09.jpg',
    artist: 'Скрябин А.В.',
    name: 'Юрьево. Яхтклуб',
    description: '25×40 см, картон, масло, 2010 г.',
    price: '9 000',
  },
  {
    id: 10,
    image: '/pic_10.jpg',
    artist: 'Тахтамышев С. А',
    name: 'Северная деревня',
    description: '75×40 см, холст, масло, 2017 г.',
    price: '36 000',
  },
  {
    id: 11,
    image: '/pic_11.jpg',
    artist: 'Царикович В.В.',
    name: 'Французский завтрак',
    description: '34×100 см, холст, масло, 2013 г.',
    price: '70 000',
  },
  {
    id: 12,
    image: '/pic_12.jpg',
    artist: 'Князев И.М',
    name: 'Весенний этюд',
    description: '60×50 см, холст, масло, 2015 г.',
    price: '34 000',
  },
];
